import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/ui/Navbar";
import NextTopLoader from "nextjs-toploader";
import WhatsappButton from "@/components/WhatsappButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Definimos el tipo del usuario (ligero)
type MockUser = {
  id: string;
  name: string;
  email?: string | null;
  image?: string;
};

type MockSession = {
  user: MockUser | null;
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const mockSession: MockSession = {
    user: {
      id: "1",
      name: "Usuario de Prueba",
      email: "test@example.com",
      image: "https://via.placeholder.com/40",
    },
  };

  const mockNoSession: MockSession = {
    user: null,
  };

  const session: MockSession = mockNoSession;

  async function signOutAction(){
    "use server"
    console.log("Cerrar sesión (simulado)");
  };

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextTopLoader
          color="#2299DD"
          initialPosition={0.08}
          crawlSpeed={200}
          height={3}
          crawl={true}
          showSpinner={true}
          easing="ease"
          speed={200}
          shadow="0 0 10px #2299DD,0 0 5px #2299DD"
          template='<div class="bar" role="bar"><div class="peg"></div></div> 
  <div class="spinner" role="spinner"><div class="spinner-icon"></div></div>'
          zIndex={1600}
          showAtBottom={false}
        />
        <Navbar //user={session?.user} signOutAction={signOutAction} 
        />
        <main>{children}</main>
        <Footer />
        <WhatsappButton />
      </body>
    </html>
  );
}
